#pragma once
#include "ImageProcessor.h"
#include "ImgProcSet.h"

#include "AverageMat.h"
#include "AverageOnline.h"
#include "ColorConverter.h"
#include "EqualizeHist.h"
#include "FeatureMatcher.h"
#include "FeatureTracker.h"
#include "Flipper.h"
#include "FlowTracker.h"
#include "GaussianBlur.h"
#include "ImagePoint.h"
#include "ImageWindow.h"
#include "Resizer.h"
#include "SubMat.h"
#include "VideoCapture.h"
#include "Convert.h"
#include "MaskCopy.h"
#include "Threshold.h"
#include "Dilate.h"
#include "Erode.h"
#include "RunningAvg.h"
#include "FitInGrid.h"

#include "OpticalFlowFarneback.h"
#include "OpticalFlowPyrLK.h"

#include "Labeling.h"
#include "LabeledObject.h"
#include "Labeler.h"
#include "TrackingObject.h"

#include "ImageDataPtr.h"
#include "cvUtils.h"

#include "pugixml.hpp"
